<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-O2V6U4O" ignored="1" name="Test" tests="21" failures="4" timestamp="2020-05-17T12:20:53 BST" time="0.53" errors="0">
  <testcase name="loginTest" time="0.055" classname="testngtests.TestExecutionOrder"/>
  <testcase name="logOutTest" time="0.011" classname="testngtests.TestExecutionOrder"/>
  <testcase name="addToCartTest" time="0.006" classname="testngtests.TestExecutionOrder"/>
  <testcase name="forgotPasswordTest" time="0.002" classname="testngtests.TestExecutionOrder"/>
  <testcase name="addMultipleItemsToCartTest" time="0.003" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="addToCartTest" time="0.004" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="deleteFromCartTest" time="0.003" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="deleteMultipleItemsFromCartTest" time="0.003" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="forgotPasswordTest" time="0.002" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="logOutTest" time="0.001" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="loginTest" time="0.002" classname="testngtests.TestCaseGroupingTest"/>
  <testcase name="forgotPasswordTest" time="0.003" classname="testngtests.TestCaseDependencyManagement"/>
  <testcase name="loginTest" time="0.014" classname="testngtests.TestCaseDependencyManagement">
    <failure type="java.lang.AssertionError" message="Login functionality is not working. expected [somethingelse] but found [something]">
      <![CDATA[java.lang.AssertionError: Login functionality is not working. expected [somethingelse] but found [something]
at testngtests.TestCaseDependencyManagement.loginTest(TestCaseDependencyManagement.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="addMultipleItemsToCartTest" time="0.0" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- addMultipleItemsToCartTest -->
  <testcase name="addToCartTest" time="0.0" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- addToCartTest -->
  <testcase name="deleteFromCartTest" time="0.0" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- deleteFromCartTest -->
  <testcase name="deleteMultipleItemsFromCartTest" time="0.0" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- deleteMultipleItemsFromCartTest -->
  <testcase name="logOutTest" time="0.0" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- logOutTest -->
  <testcase name="assertionNotEqualsTest" time="0.002" classname="testngtests.AssertionsExamplesTests">
    <failure type="java.lang.AssertionError" message="I am failure Message : Titles should not match biut they are matching.  did not expect [Something] but found [Something]">
      <![CDATA[java.lang.AssertionError: I am failure Message : Titles should not match biut they are matching.  did not expect [Something] but found [Something]
at testngtests.AssertionsExamplesTests.assertionNotEqualsTest(AssertionsExamplesTests.java:53)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- assertionNotEqualsTest -->
  <testcase name="additionToCartTest" time="0.005" classname="testngtests.SampleTest1">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at testngtests.SampleTest1.additionToCartTest(SampleTest1.java:27)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- additionToCartTest -->
  <testcase name="deletingFromCartTest" time="0.009" classname="testngtests.SampleTest1">
    <failure type="java.lang.AssertionError" message="expected [0] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [3]
at testngtests.SampleTest1.deletingFromCartTest(SampleTest1.java:46)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deletingFromCartTest -->
  <testcase name="assertionEqualsTest" time="0.0" classname="testngtests.AssertionsExamplesTests">
    <ignored/>
  </testcase> <!-- assertionEqualsTest -->
</testsuite> <!-- Test -->
