<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-O2V6U4O" name="testngtests.TestCaseDependencyManagement" tests="7" failures="1" timestamp="2020-05-23T09:50:48 BST" time="0.008" errors="0">
  <testcase name="deleteMultipleItemsFromCartTest" time="0.000" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- deleteMultipleItemsFromCartTest -->
  <system-out/>
  <testcase name="addToCartTest" time="0.000" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- addToCartTest -->
  <system-out/>
  <testcase name="loginTest" time="0.005" classname="testngtests.TestCaseDependencyManagement">
    <failure type="java.lang.AssertionError" message="Login functionality is not working. expected [somethingelse] but found [something]">
      <![CDATA[java.lang.AssertionError: Login functionality is not working. expected [somethingelse] but found [something]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at testngtests.TestCaseDependencyManagement.loginTest(TestCaseDependencyManagement.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <system-out/>
  <testcase name="addMultipleItemsToCartTest" time="0.000" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- addMultipleItemsToCartTest -->
  <system-out/>
  <testcase name="deleteFromCartTest" time="0.000" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- deleteFromCartTest -->
  <system-out/>
  <testcase name="logOutTest" time="0.000" classname="testngtests.TestCaseDependencyManagement">
    <skipped/>
  </testcase> <!-- logOutTest -->
  <system-out/>
  <testcase name="forgotPasswordTest" time="0.003" classname="testngtests.TestCaseDependencyManagement"/>
  <system-out/>
</testsuite> <!-- testngtests.TestCaseDependencyManagement -->
